apiVersion: v1
kind: Service
metadata:
  annotations:
    function: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: graphqlblog
  name: graphqlblog
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: graphqlblog
status:
  loadBalancer: {}
